# -*- coding: utf-8 -*-
"""Main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wPiJtQ_sU5YMjlzeGozEx8WVNqT0jtm0
"""

# Variabel

a = 2 #integer / bilangan bulat
hewan = "Gajah" # String
#untuk yang dasarnya tidak ada yang namanya Char
b = 'A'  # String
c = True # Boolean
d = False # Boolean
e = 2.0 # Float
f = [] # List / Array
g = {} # Dictionary
h = () # Tuple

# Print

print(hewan)
print("Singa")
print(2)
print(2+3)
print(True)

# Print 2
print("Nama hewannya adalah: " + hewan)
print("Nama hewannya adalah: {}".format(hewan))
print("Nama : {}, Tempat Tinggal : {}, Umur : {}".format("Hoshi", "Namyangju", 23))

Nama_Siswa = ["Hoshi", "Taeyong", "Jennie", "Sanha", "Felix"]

print(Nama_Siswa[0])
print(Nama_Siswa[1])
print(Nama_Siswa[2])

Nama_Siswa

List_1 = ["Hoshi"] * 4
List_1

Nama_Siswa[0:2]

Nama_Siswa[-2]

Nama_Siswa[-3:]

Nama_Siswa.append(1)
Nama_Siswa

Nama = "Hoshi"
Tempat = "Namyangju"
Umur = 23
print("Nama : {}, Tempat Tinggal : {}, Umur : {}".format(Nama, Tempat, Umur))