# -*- coding: utf-8 -*-
"""Nilai.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YDPYo6JKOF9nOM5vgWRBAfyo9n3px9Ur
"""

List_1 = ["Yulli"] * 5
print(List_1)