# -*- coding: utf-8 -*-
"""Yulli - Desy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lYQYH2jTxCvh7nlGgKlfe8WnG2CWeHhS
"""

# IT Class 2

# 1. Desy Rafika Intan Sembiring (001201900062)
# 2. Yulli Nisia (001201900069)

# Soal :
# a = input(), if else, untuk bedain dia kelipatan lima atau bukan
# 5 = True
# 10 = True
# 8 = False
# 12 = False

a = int(input("Input bilangan: "))
if a % 5 == 0:
    print(str(a) + " adalah bilangan kelipatan 5.")
else:
    print(str(a) + " bukan bilangan kelipatan 5.")